name: "Energy Smart Bridge"
description: "Energy Smart Bridge"
version: "1.0.2"
slug: "energy_smart_bridge"
image: "ghcr.io/starsoccer/energysmartbridge/{arch}"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  443/tcp: 443
ports_description:
  443/tcp: HTTPS webserver port
options:
  mqtt_port: 1883
  mqtt_host: null
  mqtt_username: null
  mqtt_password: null
  mqtt_prefix: "energysmartbridge"
  mqtt_homeassistant_prefix: "homeassistant"
  log_level: list(fatal|error|warn|info|debug|trace)
schema:
  mqtt_port: port
  mqtt_host: str
  mqtt_username: str
  mqtt_password: password
  mqtt_prefix: str
  mqtt_homeassistant_prefix: str
  log_level: list(fatal|error|warn|info|debug|trace)